#!/bin/bash

set -x
set -e

export DEBIAN_FRONTEND=noninteractive
export LD_PRELOAD=libeatmydata.so
export LD_LIBRARY_PATH=/usr/lib/libeatmydata

BUILD_DIR='/build'

if [[ ! -d "${BUILD_DIR}/kernelbakery" ]] || [[ ! -d "${BUILD_DIR}/piControl" ]] || [[ ! -d "${BUILD_DIR}/linux" ]] ; then
        >&2 echo "Missing required repos in ${BUILD_DIR}"
            exit
fi

cd ${BUILD_DIR}/kernelbakery
LINUXDIR=$PWD/../linux PIKERNELMODDIR=$PWD/../piControl debian/update.sh

if [[ ${UPDATE_CHANGELOG:-1} -eq 1 ]]; then
	BUILD_DATE=$(date "+%y%m%d%H%M%S")
	BUILD_COMMIT=$(cd ../linux && git rev-parse --short HEAD )

	debchange  -l "~${BUILD_DATE}-${BUILD_COMMIT}" -D experimental "this is an automatic build generated by the buildsystem"
fi

dpkg-buildpackage -a armhf -b -us -uc
